version = 1

test_patterns = ["*/test/**"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["angular"]
  environment = [
    "nodejs",
    "browser",
    "jest"
  ]
  dialect = "typescript"