version = 1

test_patterns = [
  "test/",
  "**/__tests__/",
  "**/*_spec.ts",
  "**/*_test.ts"
]

exclude_patterns = [
  "node_modules/",
  "dist/",
  "build/",
  "coverage/",
  "*.config.js",
  "*.config.ts"
]

[[analyzers]]
name = "typescript"

  [analyzers.meta]
  exclude = [
    "src/**/__tests__/",
    "src/**/*_spec.ts",
    "src/**/*_test.ts"
  ]
  include = [
    "src/**/*.ts",
    "src/**/*.tsx"
  ]
  tsconfig = "tsconfig.json"
  runtime_version = "nodejs@18"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["angular"]
  environment = [
    "nodejs",
    "browser",
    "jest"
  ]

[[analyzers]]
name = "eslint"

  [analyzers.meta]
  config_path = ".eslintrc.json"

[[analyzers]]
name = "coverage"

  [analyzers.meta]
  format = "lcov"
  report_path = "coverage/lcov.info"